# Generated by Django 4.2.24 on 2025-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('factory_id', models.AutoField(primary_key=True, serialize=False)),
                ('factory_name', models.CharField(max_length=40)),
                ('factory_location', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
