<<<<<<< HEAD
# Generated by Django 4.2.24 on 2025-09-07 13:46
=======
# Generated by Django 4.2.23 on 2025-09-03 07:40
>>>>>>> d7822e02be4605c4f0093b89a0afe86acc294ca4

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='EnergyEntry',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('firewood', 'Firewood')], max_length=100)),
                ('energy_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('co2_equivalent', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True)),
                ('tea_processed_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
=======
            name='EnergyEntryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(max_length=100)),
                ('energy_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tea_processed_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('co2_equivalent', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to='factory.factory')),
>>>>>>> d7822e02be4605c4f0093b89a0afe86acc294ca4
            ],
        ),
    ]
