# Generated by Django 4.2.24 on 2025-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyEntry',
            fields=[
                ('data_id', models.AutoField(primary_key=True, serialize=False)),
                ('energy_type', models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('firewood', 'Firewood')], max_length=100)),
                ('energy_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('co2_equivalent', models.DecimalField(blank=True, decimal_places=4, editable=False, max_digits=10, null=True)),
                ('tea_processed_amount', models.DecimalField(decimal_places=4, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='factory.factory')),
            ],
        ),
    ]
