# Generated by Django 4.2.23 on 2025-09-03 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyEntryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy_type', models.CharField(max_length=100)),
                ('energy_amount', models.DecimalField(decimal_places=4, max_digits=15)),
                ('tea_processed_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('co2_equivalent', models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to='factory.factory')),
            ],
        ),
    ]
