# Generated by Django 4.2.23 on 2025-09-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('energy_entry_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyentrydata',
            name='energy_type',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('diesel', 'Diesel'), ('firewood', 'Firewood')], max_length=100),
        ),
    ]
