# Generated by Django 4.2.22 on 2025-09-04 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('energy_entry_data', '0002_alter_energyentrydata_energy_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyentrydata',
            name='factory',
        ),
        migrations.AddField(
            model_name='energyentrydata',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to=settings.AUTH_USER_MODEL),
        ),
    ]
