# Generated by Django 4.2.22 on 2025-09-05 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('energy_entry_data', '0003_remove_energyentrydata_factory_energyentrydata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energyentrydata',
            name='user',
        ),
        migrations.AddField(
            model_name='energyentrydata',
            name='factory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to='factory.factory'),
        ),
    ]
