# Generated by Django 4.2.24 on 2025-09-05 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0001_initial'),
        ('energy_entry_data', '0004_remove_energyentrydata_user_energyentrydata_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyentrydata',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='energy_entries', to='factory.factory'),
        ),
    ]
