# Generated by Django 4.2.24 on 2025-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCU',
            fields=[
                ('mcu_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(default='active', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('factory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcus', to='factory.factory')),
            ],
        ),
    ]
