# Generated by Django 4.2.24 on 2025-09-07 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emissions',
            fields=[
                ('emissions_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=255)),
                ('emission_rate', models.DecimalField(decimal_places=15, max_digits=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('factory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='factory.factory')),
            ],
        ),
    ]
